# Generated by Django 4.2.5 on 2023-10-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profileIMG',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
