# Generated by Django 4.2.5 on 2023-10-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_recipe_recipegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipegroup',
            name='name',
            field=models.CharField(default='Recipe Group', max_length=300),
        ),
    ]
