# Generated by Django 4.2.5 on 2023-12-04 20:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.CharField(default='[]', max_length=2048)),
                ('instructions', models.CharField(default='[]', max_length=2048)),
                ('week_time', models.DateTimeField(null=True)),
                ('vote_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('django_group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Recipe Group', max_length=300)),
                ('privacy', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], default='PRIVATE', max_length=10)),
                ('current_poll_time', models.DateTimeField(null=True)),
                ('current_poll', models.BooleanField(default=0, null=True)),
                ('current_recipe', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe')),
                ('django_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_poll_time', models.DateTimeField(null=True)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe')),
                ('recipe_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipegroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_poll_time', models.DateTimeField(null=True)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('recipe_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipegroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
