# Generated by Django 4.2.5 on 2023-12-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollRecipe',
        ),
    ]
