# Generated by Django 4.2.5 on 2023-12-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_pollrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
