# Generated by Django 4.2.5 on 2023-10-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_week_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='week_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipegroup',
            name='current_poll_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
