# Generated by Django 4.2.5 on 2023-11-06 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('recipes', '0006_alter_recipe_week_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='django_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
    ]
