# Generated by Django 4.2.5 on 2023-11-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_django_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipegroup',
            name='current_poll',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
