# Generated by Django 4.2.5 on 2023-11-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipegroup_current_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(default='[]', max_length=2048),
        ),
    ]
