# Generated by Django 4.2.5 on 2023-11-26 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0009_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipegroup',
            name='current_poll_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_poll_time', models.DateTimeField(null=True)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe')),
                ('recipe_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipegroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
